services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/app
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
    ports:
      - "3000:3000"
