version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./voice_outputs:/app/voice_outputs

  web:
    build:
      context: .
      dockerfile: web/Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - api



networks:
  app-net:
    driver: bridge
