FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip \
    && pip install "setuptools<70" "wheel<0.43" "cython<3.0" \
    && pip install --no-cache-dir -r requirements.txt

COPY ./api /app/api

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "5000"]
